spring:
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
    static-path-pattern: /static/**
  datasource:
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: oracle.jdbc.driver.OracleDriver
     url: jdbc:oracle:thin:@localhost:1521:orcl
     username: sa
     password: sa
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false
  redis:
    database: 0
    host: 192.168.159.10
    port: 6379
    password: 123456
  session:
    store-type: none

server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml